#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2017/8/7
# @Author  : chex
__title__ = ''
__description__ = """
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms
"""
__description_cn__ = """
斐波那契数列的每一个新项等于前两项之和。从1、2开始，前10项是：1、2、3、5、8、13、21、34、55、89.
求出斐波那契数列中不超过4000000的所有偶数项之和
"""
num_prev = 1
num = 2
result = 2
while num < 4000000:
    num_prev, num = num, num + num_prev
    if num % 2 == 0:
        result += num
print result
# 4613732


